baseURL = "http://example.org/"
languageCode = "en-us"

theme = "cactus"
title = "Gaganpreet Arora"

[markup.goldmark.renderer]
unsafe= true


[params]
  colortheme = "classic" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  description = "Hi, I am Gaganpreet, a software engineer based in the Netherlands."
  mainSection = "posts"
  postsOnHomePage = 5
  tagsOverview = false
  logo = "/images/me.jpg"
  favicon = "/images/favicon.ico"

  [params.comments]
    enabled = true # default
    engine = "disqus" # more supported engines will be added.

  [[params.social]]
    name = "github-alt"
    link = "https://github.com/gaganpreet"
  [[params.social]]
    name = "goodreads"
    link = "https://www.goodreads.com/user/show/7515314-gaganpreet-arora"
  [[params.social]]
    name = "gitlab"
    link = "https://gitlab.com/gaganpreet"
  [[params.social]]
    name = "linkedin"
    link = "https://in.linkedin.com/in/gaganpreetarora"
  [[params.social]]
    name = "email"
    link = "hey@gaganpreet.in"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/_gagan"
  [[params.social]]
    name = "lastfm"
    link = "https://www.last.fm/user/gaganpreet"
